openapi: 3.0.0
info:
  title: TaaS平台接口
  version: 1.0.0
  description: TaaS平台设计方案
paths:
  /userlogin/v1/get-captcha:
    get:
      tags:
        - userManager
      description: 向前端提供图形验证码
      operationId: getCaptcha
      parameters:
        - description: '旧图形验证码id, 不为空表示刷新'
          schema:
            type: string
          name: captchaId
          in: query
        - description: 图形高度
          schema:
            type: string
          name: height
          in: query
        - description: 图形宽度
          schema:
            type: string
          name: width
          in: query
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                required:
                  - captchaId
                  - captcha
                properties:
                  optResult:
                    type: number
                  msg:
                    type: string
                  captchaId:
                    type: string
                    description: 图形验证码唯一ID
                  captcha:
                    type: string
                    description: 图形验证码base64字符串
  /userlogin/v1/login:
    post:
      tags:
        - userManager
      description: 用户登录平台
      operationId: userLogin
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - loginType
              properties:
                loginType:
                  type: string
                  description: 用户登录类型： account– 帐号密码登录 mobile– 手机号码登录 wechat– 微信账号登录
                accountLoginParam:
                  type: object
                  description: 帐号密码登录参数，当用户登录类型为account时，此参数有效
                  required:
                    - loginname
                    - password
                  properties:
                    loginname:
                      type: string
                      description: 登录帐号
                    password:
                      type: string
                      description: 登录密码
                    authcode:
                      type: string
                      description: 认证码，防止频繁登录
                mobileLoginParams:
                  type: object
                  required:
                    - mobilePhone
                    - password
                    - smsAuthCode
                  properties:
                    mobilePhone:
                      type: string
                    password:
                      type: string
                    smsAuthCode:
                      type: string
                wechatLoginParams:
                  type: object
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  optResult:
                    type: string
                  msg:
                    type: number
                  residualTimes:
                    type: number
                    description: 账号密码输入错误剩余次数
                  userId:
                    type: string
                  nickName:
                    type: string
                  roleType:
                    type: string
                  sessionId:
                    type: string
                  roleFrontAuthInfo:
                    type: object
                    description: 用户角色的前端授权访问信息对象
                    properties:
                      frontsysId:
                        type: number
                        description: 授权访问的前端系统ID
                      frontSysName:
                        type: string
                        description: 授权访问的前端系统名称
                      menus:
                        type: array
                        items:
                          $ref: '#/components/schemas/Menu'
      security: []
      summary: ''
  /users/v1/logout:
    post:
      tags:
        - userManager
      description: 用户登出平台
      operationId: userLogout
      responses:
        '200':
          $ref: '#/components/responses/CommonResponse'
  /users/v1/add-area:
    post:
      tags:
        - userManager
      description: 增加一个地区
      operationId: addArea
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - sort
                - code
                - type
              properties:
                parentId:
                  type: string
                  description: 父地区ID。如果为一级地区，则不带此参数项
                parentIds:
                  type: array
                  items:
                    type: string
                  description: 父地区ID列表
                name:
                  type: string
                sort:
                  type: string
                  description: 排序
                code:
                  type: string
                  description: 地区代码
                type:
                  type: string
                  description: 地区类型（1：国家；2：省份、直辖市；3：地市；4：区县）
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                description: 需要返回地区ID
                properties:
                  optResult:
                    type: number
                  msg:
                    type: string
                  id:
                    type: string
                    description: 地区ID
  '/users/v1/delete-area/{id}':
    delete:
      tags:
        - userManager
      operationId: deleteArea
      parameters:
        - description: 地区ID
          required: true
          schema:
            type: string
          name: id
          in: path
      responses:
        '200':
          $ref: '#/components/responses/CommonResponse'
  '/users/v1/get-area/{id}':
    description: 查询一个地区信息
    get:
      tags:
        - userManager
      operationId: getArea
      parameters:
        - description: 地区ID
          required: true
          schema:
            type: string
          name: id
          in: path
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                required:
                  - optResult
                  - name
                  - sort
                  - code
                  - type
                  - parentId
                  - parentIds
                properties:
                  optResult:
                    type: number
                  msg:
                    type: string
                  name:
                    type: string
                  sort:
                    type: string
                  code:
                    type: string
                  type:
                    type: string
                    description: 地区类型（1：国家；2：省份、直辖市；3：地市；4：区县）
                  parentId:
                    type: string
                    description: 父级地区id
                  parentIds:
                    type: string
                    description: 所有父级地区id
  /api/test/1:
    get:
      summary: ''
      operationId: getApiTest
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/TestModel1'
                  - $ref: '#/components/schemas/TestModel2'
components:
  schemas:
    Menu:
      type: object
      description: 菜单信息列表
      properties:
        id:
          type: number
          description: 菜单项ID号
        parentId:
          type: number
          description: 菜单项的父菜单ID号，如果为顶级菜单则此项值为0
        menuname:
          type: string
          description: 菜单项名称
        uri:
          type: string
          description: 菜单项访问uri路径
        menus:
          type: array
          description: 本菜单项下子菜单对象列表
    CommonResponse:
      type: object
      description: 默认返回
      required:
        - optResult
      properties:
        optResult:
          type: number
          description: 值为0，操作成功
        msg:
          type: string
          description: 操作失败说明
    TestModel1:
      title: TestModel1
      type: object
      properties:
        id:
          type: number
    TestModel2:
      title: TestModel2
      type: object
      properties:
        name:
          type: string
        sex:
          type: boolean
  responses:
    CommonResponse:
      description: 常规默认成功返回
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CommonResponse'
  securitySchemes:
    userId:
      type: apiKey
      name: userId
      in: header
      description: 用户标识
    sessionId:
      type: apiKey
      name: sessionId
      in: header
      description: 会话标识
tags:
  - name: userManager
    description: 账户中心服务
  - name: ssoServer
    description: 单点登录管理服务
security:
  - userId: []
    sessionId: []
